### ISSUE TITLE
Feature Request: Reverse min and max

### ISSUE THREAD

**Issue by leerogers** [toorshia/justgage#113]
A great option could be to have the ability to have max on the left and min on the right to be able to do countdown like activities.  Or have the bigger number on the left, smallest on right.  Tried reversing and doesn't render correctly.

**Comment by krasslex** [comment]
This would be a great feature. Please implement.

**Comment by toorshia** [comment]
It's already developed, doing some final testing, should be up and running soon

**Comment by AdamMarsden** [comment]
Anything been pushed for this?

**Comment by toorshia** [comment]
Just pushed out this feature - http://justgage.com/examples/reverse.html
