### ISSUE TITLE
Update Bower

### ISSUE THREAD

**Issue by LostCrew** [toorshia/justgage#115]
I really don't understand which package i have to consume on bower. on `bower search gage`, i get this:

```
justgage git://github.com/Ulflander/justgage.git
justgage-bower git://github.com/remasis/justgage.git
JustGage git://github.com/agaskell/justgage.git
```

none of them refer to this repository. it must be very confusing for other users as well.
thanks.

**Comment by toorshia** [comment]
I've just created a release. From what I understand, that should be enough for Bower tracking?

**Comment by frapontillo** [comment]
@toorshia no, you should also [register](http://bower.io/docs/creating-packages/#register) it.

**Comment by toorshia** [comment]
Just checked bower registry, looks like it picked up github tag/release based on existing bower.json spec.
