### ISSUE TITLE
a float value

### ISSUE THREAD

**Issue by gejiawen** [toorshia/justgage#116]
How to set value from min to max with a float number?

For example:

min = 0
max = 10

the value can be shown with 1.23 or 4.6, etc.

Maybe I can set the precision?

**Comment by kanesee** [comment]
I believe you can just add the "decimals: true" attribute.

          var g = new JustGage({
            id: 'gauge',
            decimals: true,
            value: 4.6,
            min: 0,
            max: 10
          });

**Comment by leshacat** [comment]
This is confirmed fix... Issue can be closed...

Although it would be nice to know how to increase decimal points from one to two... Thanks
