### ISSUE TITLE
How to avoid top space and make full dimension ?

### ISSUE THREAD

**Issue by athimannil** [toorshia/justgage#118]
Is there any option to avoid top space. 
Actually I am looking solution to show as full width and full height.

![screen shot 2014-03-13 at 23 19 44](https://f.cloud.github.com/assets/4364227/2416533/d88e5d18-ab06-11e3-99f6-9649bf9b7f3a.png)

here is the code 
`
var g = new JustGage({
  id: "spedometer", 
  value: 1645, 
  min: 0,
  max: 2450,
  shadowOpacity: 0,
  relativeGaugeSize: true
});
`

**Comment by toorshia** [comment]
Title space will be removed in next version. Thanks
