### ISSUE TITLE
Error: Invalid value for <rect> attribute width="100%99"

### ISSUE THREAD

**Issue by j0hnb** [toorshia/justgage#119]
In my console i'm seeing a large amount of Invalid value errors.

Error: Invalid value for <rect> attribute width="100%99" raphael-min.js:1445
Error: Invalid value for <rect> attribute height="100%99" raphael-min.js:1445
Error: Invalid value for <rect> attribute width="100%99" raphael-min.js:1445
Error: Invalid value for <rect> attribute height="100%99" raphael-min.js:1445
Error: Invalid value for <rect> attribute width="100%99" raphael-min.js:1445
Error: Invalid value for <rect> attribute height="100%99" raphael-min.js:1445
....

**Comment by gslisrael** [comment]
I found the source of the problem and a possible fix. In raphael-min.js find this string: "this.width+99,this.height+99" and remove each "+99".

That section is part of some kludge for Safari. I'm not sure if or why it was necessary.

**Comment by KaviSharma** [comment]
workaround: 
in raphael-min.js change this line
```javascript
this.width+99,this.height+99
```
with this line
```javascript
parseInt(this.width)+99,parseInt(this.height)+99)
```

**Comment by toorshia** [comment]
OK, so clearly Raphael issue, can't do much about it :) Closing
