### ISSUE TITLE
Add increments to the value

### ISSUE THREAD

**Issue by alib0ng0** [toorshia/justgage#121]
Hi there - firstly let me say i love the work you've done - very clean and simple.

I figured out how to get the graphs to display a percentage using g1.refresh(60); - what i would like to do is add +10 or -40 to the current value - is this possible?

Many thanks
Al

**Comment by toorshia** [comment]
Hi there, thanks for kind words. At the moment you can only update with new value. I believe you should keep whatever logic you have for differentiating/incrementing the value separate of the gauge logic. Gauge is not a data-keeping object, but rather a mere visualisation. This way you can apply whatever logic you decide to go for, and just feed the gauge with updated value to change visuals.
What's your opinion on this?
