### ISSUE TITLE
Browser crashing on iOS when holding finger on text to select it

### ISSUE THREAD

**Issue by zilions** [toorshia/justgage#127]
This is no major bug, but it does cause the browser to crash every time, so I thought that I would mention it here.

When I attempt to hold my finger on the text (either the value text in the middle, or the min/max text at either end) the browser will crash.

I have tested this issue on both iPhone 5 and iPad 2. I have tested on iOS 7.1 and iOS 7.1.1 with both Chrome for iOS and Safari for iOS.

**Comment by toorshia** [comment]
Hi, just tested on iOS 6 and iOS9, seems to work OK. Text is selected, no browser crashing.
