### ISSUE TITLE
Values in Multiple Gage

### ISSUE THREAD

**Issue by ParthGajjar** [toorshia/justgage#132]
i almost managed how to show multipe gage
currently i just hide value.
i just need to show value of that guage in proper way

Here screenshot and code
 
![download 6](https://cloud.githubusercontent.com/assets/6904163/3227599/e790851e-f07c-11e3-8b6e-8995e74c1d1a.png)

https://gist.github.com/ParthGajjar/9727ad999d5ef40e69af

**Comment by brunotourinho** [comment]
any progress on this?

**Comment by toorshia** [comment]
Similar to #33. I plan to investigate feasibility of this approach a bit more, if it turns out to bee a good feature, I'll do it.
