### ISSUE TITLE
Invalid value for <path> attribute d="Z"

### ISSUE THREAD

**Issue by AlfredTheJeep** [toorshia/justgage#133]
I have this function:

function drawIt() {
  var g = new JustGage({
    id: "tempgauge",
    value: 67,
    min: 0,
    max: 100,
    title: "Visitors"
  });
}

If I call it inside script tags, everything works great.

If I call it via body onload="drawIt()", then I get these errors, because jQuery is hiding the gauge.

Error: Invalid value for <path> attribute d="Z" raphael.2.1.0.min.js:10
q raphael.2.1.0.min.js:10
w raphael.2.1.0.min.js:10
A.attr raphael.2.1.0.min.js:10
JustGage justgage.1.0.1.min.js:12
drawIt alfred.js:34
onload alfred.html:59

Is there a way to draw a gauge that isn't currently visible?

**Comment by azlochevsky** [comment]
zeroasterisk, thank you soooo very much. I had width abd height but not display and this made all the difference in the world! You totally rock!

**Comment by Thecompanymerchant** [comment]
@jasonshark many thanks for your comment about parseTime - i was using labels as "Jan 2015", "Feb  2015" etc and paarseTime: false solved my problem with Morris. Much obliged
