### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by jeffcorey** [toorshia/justgage#134]
Great plugin everyone. I was wondering if there is anyway to override the css to make these smaller using media queries? I know that there are a few different sizes but we need this to be responsive.  Please let us know. 
Thanks

**Comment by pbaumard** [comment]
See http://justgage.com/demos/responsive-gauges/ which uses a "work-in-progress, unreleased, unofficial code", as written in http://justgage.com/justgage.js header.
