### ISSUE TITLE
Error messages with Cordova

### ISSUE THREAD

**Issue by leydar** [toorshia/justgage#137]
I'm using justgage via the Intel XDK implementation of the appdesigner/Bootstrap interface. Dropping a justgage into the app and running the emulator results in a series of errors. 'Error: Invalid value for rect attribute height="100%99"' It seems to work fine besides this. The auto-generated html is 'div class="uib-justgage gauge no_wrap widget uib_w_27" data-uib="widgets/justgage" data-ver="0" id="uib-justgage-0" data-gauge="{'title':'Gauge','value':50,'min':0,'max':100,'hideMinMax':0,'hideValue':0,'hideInnerShadow':1}" /div'

Cheers

**Comment by toorshia** [comment]
Hi, thanks for your interest in justgage :)
Unfortunately, I can't really offer support for integration issues like these - there's simply too many libraries to support. I am sure you already worked out something in the meantime :) Thanks again!
