### ISSUE TITLE
Feature Request - give title, value css classes

### ISSUE THREAD

**Issue by hubatish** [toorshia/justgage#139]
I've been using justgage for a while now, and it's great!  Some of the customization is lacking though.  I would like to change the font and font-size of the title, but there is no option to do so.  Rather than just adding more options though, I'm wondering if I can apply those changes via css or jquery?  
If the title and different sections had class="gageTitle" or some such, I could get a ton of customization by changing those values myself.

**Comment by scottsb** [comment]
Vote for this! Having to specify all the styles in JavaScript reminds me of <font> tags and <blink>. (Shudder.) This should be able to be controllable by CSS. Right now it's not possible without really ugly (and fragile) hacking with sibling selectors.

**Comment by ET-CS** [comment]
+1

**Comment by toorshia** [comment]
Title will be removed in next release, so you can have it as a part of HTML :) For other labels, I'll see what is possible via CSS, otherwise I'll add options for adjusting style. Thanks
