### ISSUE TITLE
Error when using responsive gauges

### ISSUE THREAD

**Issue by bykbtzr** [toorshia/justgage#141]
After adding the option `relativeGaugeSize: true` I've started to get the following error in console that is preventing my controller initialization to finish:

`Error: Invalid value for <svg> attribute preserveAspectRatio="meet" raphael.2.1.0.min.js:10`
Stacktrace:

```
q raphael.2.1.0.min.js:10
a._engine.setViewBox raphael.2.1.0.min.js:10
k.setViewBox raphael.2.1.0.min.js:10
JustGage justgage.1.0.1.js:333
(anonymous function) resources.js:612
x.extend.each jquery-1.10.2.js:659
x.fn.x.each jquery-1.10.2.js:266
DashboardSystemResources.createGaugeMeters resources.js:606
DashboardSystemResources.init resources.js:94
DashboardController.build dashboard.js:13
Controllers.buildCurrent controllers.js:77
Loader.processContent loader.js:136
x.event.dispatch jquery-1.10.2.js:5098
v.handle jquery-1.10.2.js:4774
x.event.trigger jquery-1.10.2.js:5012
(anonymous function) jquery-1.10.2.js:5694
x.extend.each jquery-1.10.2.js:659
x.fn.x.each jquery-1.10.2.js:266
x.fn.extend.trigger jquery-1.10.2.js:5691
fire jquery.pjax.js:185
(anonymous function) jquery.pjax.js:321
loadNextScript jquery.pjax.js:731
newScript.onload.newScript.onerror
```

Chrome 36.0.1985.125 m

**Comment by mattjared** [comment]
@toorshia Just a head's up: justgage.com has the old version of Raphael so this error / issue is persistent if you don't download justGage from Github or download a newer version of Raphael separately. Thanks for all your hard work on justGage, really enjoy using it!

**Comment by toorshia** [comment]
Thanks man, I'll update the website :)
