### ISSUE TITLE
Does not display correctly when canvas width is smaller than canvas height

### ISSUE THREAD

**Issue by pieterjandesmedt** [toorshia/justgage#146]
[See the error in this fiddle](http://jsfiddle.net/vg3zj96h/1/)

Due to the `this.canvas.customAttributes.pki ` path parameter formulas being wrong:

```javascript
Cx = w / 2 + dx,
Cy = h / 1.25 + dy,

Xo = w / 2 + dx + Ro * Math.cos(alpha),
Yo = h - (h - Cy) + dy - Ro * Math.sin(alpha),
Xi = w / 2 + dx + Ri * Math.cos(alpha),
Yi = h - (h - Cy) + dy - Ri * Math.sin(alpha),
```
should be
```javascript
Cx = w / 2 + dx,
Cy = h / 1.25 + dy,

Xo = Cx + Ro * Math.cos(alpha),
Yo = Cy - Ro * Math.sin(alpha),
Xi = Cx + Ri * Math.cos(alpha),
Yi = Cy - Ri * Math.sin(alpha),
```

because
* ` h - (h - Cy)` equals `Cy` 
* `Cy` is defined as `h / 1.25 + dy`, which contains the `+ dy` already --> **this causes the error**
* `Cx = w / 2 + dx` is also already defined.

I have not checked if this works for donut gauges.

**Comment by Remiz** [comment]
I confirm this issue. Gage looks weird when width is too small.

**Comment by toorshia** [comment]
Thanks, I've updated code with your formula :)
