### ISSUE TITLE
Change "gaugeColor" when value is 0

### ISSUE THREAD

**Issue by Keionu** [toorshia/justgage#147]
Great project!
I'm trying to implement this in a project of mine. One feature I'm missing straight away is to easier visualize when the value is 0. I have my gauge showing colors "red-yellow-green" from empty to full, but when it is all empty, all that is left is the background.

It would be really great to be able to show this better.

I tried 
g.setAttribute("gaugeColor","#cc0000");
when ever the value was one, but this doesn't run.

**Comment by toorshia** [comment]
I understand your need from UX perspective. I will research some other ideas to highlight gauge in specific cases (value 0 or some other set value). Thanks

**Comment by toorshia** [comment]
Watch #65
