### ISSUE TITLE
add an optional 'label' parameter to refresh

### ISSUE THREAD

**Issue by keulemaster** [toorshia/justgage#150]
Hello!

can you please add an other refresh() method, similar to refresh(val, max) to update the label everytime you refresh the value. Thanks! 

PS: Or just send me just the snipplet, i am not familiar with JS.

**Comment by toorshia** [comment]
Hi, refresh will receive a major modification, so you'll be able to update pretty much any parameter.

**Comment by toorshia** [comment]
Hi, new refresh method will support updating pretty much all parameters.
