### ISSUE TITLE
Add support for ranges

### ISSUE THREAD

**Issue by webdes03** [toorshia/justgage#158]
It would be nice if you could specify a low value and high value and adjust either. As an example, I want to display a range of temperatures and paint the actual low to actual high on one gauge. Say the gauge has a min of 0 and a max of 100, an ability to paint between 20 and 75.

**Comment by toorshia** [comment]
Can you send a sketch / design of this? I don't relly get it 100%. Should the gauge portion be painted all the time? Thanks.

**Comment by toorshia** [comment]
#170
