### ISSUE TITLE
Not showing in Firefox

### ISSUE THREAD

**Issue by zadro** [toorshia/justgage#161]
Your responsive example doesn't work in Firefox. Any ideas?

**Comment by toorshia** [comment]
Hi, I've just tried it and it works perfectly (firefox 36 on OSX 10.10.12). Hm?

**Comment by zadro** [comment]
https://zadroweb.com/tools/justgage.html

**Comment by zadro** [comment]
I'm on Firefox 38..maybe issue there?

**Comment by zadro** [comment]
We use your gauges for our SEO Auditor here https://zadroweb.com/seo-auditor/

**Comment by toorshia** [comment]
Nope, I've just updated to 38 and tested again, everything works.
http://justgage.com/demos/responsive-gauges/

**Comment by zadro** [comment]
That's strange. It does now for me as well. Thanks so much!
