### ISSUE TITLE
Can we start path from some less distance from current value ?

### ISSUE THREAD

**Issue by amit-rana** [toorshia/justgage#162]
Currently with new value chat update path from 0 to the value .. 

But can we have something like this 
in image i have rounded on first two chart 

not start from 0 th position, get value , minus some and plus some value based on some new width attr and draw path 

![screenshot from 2015-06-05 21 28 10](https://cloud.githubusercontent.com/assets/8027180/8009972/10eda356-0bca-11e5-8d22-2adc0cd2f77e.png)

**Comment by toorshia** [comment]
Sorry, but I don't understand what are you trying to achieve with this? Can you explain further? Thanks

**Comment by amit-rana** [comment]
ok when we have value 10 our path start making arc from 0 to 10 right ?
but what I was trying is rather than drawing arc 0 to 10 we can show arc 8 to 12 and 10 will be center of arc just like dialer pointer but arc pointer

**Comment by toorshia** [comment]
I understand, there is already a request for "arc angle" - #18. Closing this as duplicate
