### ISSUE TITLE
CustomSectors doesn't work

### ISSUE THREAD

**Issue by gaetan29** [toorshia/justgage#164]
Hi,
Thanks for your great product !

I am trying to set a gage with custom colors, but it only show the default ones, not the one set up in the following code:

      var g1 = new JustGage({
          id: "g1", 
          value: value_gauge01, 
          min: 0,
          max: 50,
    	  gaugeWidthScale: 0.6,

          valueFontColor: "white",
                    customSectors: [{
      					   color : "#99FF66",
      					   lo : 0,
      					   hi : 22},{
      					   color : "#FF9900",
      					   lo : 22,
      					   hi : 27}, {
      					   color : "#FF0066",
      					   lo : 27,
      					   hi : 50
      					   }],
      					   
      	  counter: true,
      	  title: "JARDIN",
      	  label: "C",
          valueFontColor: "white"

      });

Could you tell me what I am doing wrong please ?
Thanks & regards.

GL29

![jardin01](https://cloud.githubusercontent.com/assets/788375/8681164/318fbd28-2a66-11e5-8061-720cade214c1.jpg)

**Comment by gaetan29** [comment]
Hi,
After more testing, I managed to make it work.
Basically, the contents of justgage.js on the demo page (http://justgage.com/demos/custom-sectors/) is different from the file in the download package (justgage.1.0.1.js) ...

I did not investigate further but my code was apparently correct as it works with the version of the file just gage.js.

Regards

**Comment by gaetan29** [comment]
Me again ...
I am afraid I have another small issue with the file justgage.js .... The decimal don't show anymore (i.e.: showing 21 instead of 21.4)

I have tried to parameter       	  humanFriendlyDecimal: 1     without any luck :-(

GL29

**Comment by brunotourinho** [comment]
same problem here

**Comment by toorshia** [comment]
Are you using github or website version of library? Please use github version. The website is outdated.

**Comment by gaetan29** [comment]
When I use Github version, the decimals are not showing but the customSectors colors function does work.
When I use the website version, the decimals are showing but the customSetors colors function doesn't work.

**Comment by toorshia** [comment]
With github version, you have to explicitly set decimals option.
http://justgage.com/demos/custom-sectors/

**Comment by OyeBenny** [comment]
CustomSectors parameters don't work here as well. 
April 2018
