### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by videophonegeek** [toorshia/justgage#168]
What are the issues from keeping this from the main branch? (other than we have day jobs! :^) I am using it without the donut feature but the reponsive version looks good in the app I am building.

**Comment by toorshia** [comment]
What do you mean "keeping it from the main branch?" There's only one master branch :)

**Comment by videophonegeek** [comment]
Sorry if it is an error on my end, but "relativeGaugeSize: true" was not in my download here--only on the branch. Definately not in the Intel XDK version.

**Comment by toorshia** [comment]
Ahh, now I understand :) Didn't know someone actually bundled justgage in Intel XDK, and I'm certainly not the one maintaining justgage version inside Intel XDK. 
You can always grab latest source from github ;) Cheers.
