### ISSUE TITLE
Relative gauge size is not contained in the zip downloaded from justgage.com

### ISSUE THREAD

**Issue by videophonegeek** [toorshia/justgage#169]
After the close of the last issue, I went back and compared all three versions:

1. Intel XDK -- does not contain relativegaugesize
2. Download .zip from justgage.com --does not contain relativegaugesize
3. Github main -- OK
4. Example responsive on justgage.com uses the github version which is OK

What needs to be updated is the download on justgage.com!

**Comment by toorshia** [comment]
I've updated the download package on website. Thanks!

**Comment by videophonegeek** [comment]
Thanks for bearing with me and updating the download package on the website.
