### ISSUE TITLE
Blank space if title is empty

### ISSUE THREAD

**Issue by lukasjuhrich** [toorshia/justgage#172]
The gauge does not change its positioning to _not_ leave space above it when no title is given.

This creates an unfortunate design flaw in a webpage. Not using the builtin title should work as a valid option.

---

![gauge](http://i.imgur.com/wzrPWmN.png)

---
```javascript
$(function(){
    new JustGage({
        id: "trafficgauge",
        value: "63",
        min: 0,
        startAnimationTime: 0,
        relativeGaugeSize: true,
        max: 63,
        label: "GiB",
        levelColors: ["#ff7f7f", "#ffff7f", "#7fff7f"]
    });
});
```

**Comment by toorshia** [comment]
This is by design. Will change in next releases.
