### ISSUE TITLE
customSectors over max value

### ISSUE THREAD

**Issue by danielemams** [toorshia/justgage#173]
Hi everyone.
I used this good plugin and i would like to use the customSectors over the max value.
I modified the source and i would like to show. Maybe it would help someone else.

I put code on pastebin.
Here the link: http://pastebin.com/fhFwNbbh
My first fix is in line: 597.
My second fix is in line: 936.
With the second fix you can initialize a justgage in this way:

```javascript
graph = new JustGage({
                ...,
                customSectors: [{
                    color : "#85A137",
                    lo : 0,
                    hi : 100
                 }, {
                    color : "#CE1B21",
                    lo : 100
                }]
});
```

So I use a color from x>0 && x<=100. (#85A137).
And another color over 100, x>100. (#CE1B21).

Thanks.

**Comment by toorshia** [comment]
Hey there! 

Thanks for this one. 
I'll give it a consideration and perhaps update the original code.
