### ISSUE TITLE
Symbol on left side

### ISSUE THREAD

**Issue by muhammadahmed-ma** [toorshia/justgage#181]
How to add a symbol on left side of value, instead of right side of the value.

**Comment by toorshia** [comment]
Using symbol property, you can't do it right now. You could try using textRenderer function and bake your custom value with symbols and everything :)

**Comment by tekagami** [comment]
or just do a simple hack of the already rendered code
```
document.getElementsByTagName('tspan')[3].innerHTML='$0.00'; //// for min
document.getElementsByTagName('tspan')[4].innerHTML='$200,000.00'; //// for max
```
you would just need to adjust the part from document to the right to target the right part

**Comment by MilesHart** [comment]
` textRenderer: formatter,`

then create a function for this...

```
function formatter(val){
                return '£' + val;
            }
```
