### ISSUE TITLE
No pointer for donut

### ISSUE THREAD

**Issue by Pierre-Lannoy** [toorshia/justgage#182]
Hello!
It's seems impossible to have a pointer rendered when `donut:true`. Is it a bug, or 'by design"?

**Comment by toorshia** [comment]
It's by design :) But I agree, it should be available for donut mode as well :)

**Comment by Pierre-Lannoy** [comment]
Thanks for your answer, Bojan!
Yes, it would allow us to do a complete angle indicator (useful to indicate from where the wind comes from, in particular... uh... in my case :innocent:)

**Comment by Pierre-Lannoy** [comment]
Hi Bojan!
I guess everyone asks you this question (and I'm sorry to do like everyone else): do you have an estimation for when this can be done?

**Comment by toorshia** [comment]
Hi Pierre,

I can give you an estimation, but I cannot guarantee any dates. I'll try cooking up something tomorrow, and send you update on progress ;)

**Comment by Pierre-Lannoy** [comment]
You're a king! Great news.

**Comment by toorshia** [comment]
Voilà! :) http://justgage.com/examples/pointer.html

**Comment by Pierre-Lannoy** [comment]
YES \o/
Excellent!
Thanks for all...
