### ISSUE TITLE
Enhancement: finish angle

### ISSUE THREAD

**Issue by brunocascio** [toorshia/justgage#183]
Similitar to idea #17, can someone add the `donutFinishAngle` option?

thanks :dancer:

**Comment by toorshia** [comment]
Hi,

The way I see it, donut finishes after 360 degrees, wherever you set the starting angle :)

How would you utilise a donut which is not finished as a full circle? (i.e start angle is 90, end angle is -180)

**Comment by brunocascio** [comment]
Yes, i used startAngle with e.g 300, and `max` value 280 :) Thanks!

**Comment by andercard** [comment]
would be good to be good to make other algos example http://ashalom.github.io/GaugeMeter/

**Comment by toorshia** [comment]
Yes, I am planning to include angle feature in "regular" version. Donut, however, will remain a full circle. Not messing with the donuts man, imagine all those cops breathing down my neck :D
