### ISSUE TITLE
access min value programmatically 

### ISSUE THREAD

**Issue by NSchnitzler** [toorshia/justgage#184]
Is it possible to change the scale minimum value like the max value (gg1.refresh(gg1.originalValue, 10) ?
If not, it would be a nice additional feature.

**Comment by toorshia** [comment]
Actually, I'm planning to implement update method, which will enable control over every existing parameter :)

**Comment by NSchnitzler** [comment]
would be really nice to have these features!
Do have a schedule for that?

**Comment by toorshia** [comment]
I guess I'd like to do it by the end of January, but I'm not really promising anything here :)

**Comment by NSchnitzler** [comment]
sounds good, than i will relax and wait for news :-)

**Comment by NSchnitzler** [comment]
I wanted friendly ask if we have a chance to get an update?

**Comment by toorshia** [comment]
Wow, it's already end of March! Reminder to myself: never ever give out any dates or deadlines :)
I'm on holidays at the moment. Maaaaaybe I can patch up something quickly while I'm contemplating on update function....

**Comment by toorshia** [comment]
You can now use config object when calling refresh fn :) Big thanks to @chrismruterford!

**Comment by NSchnitzler** [comment]
Great work! But could we get an small example?

**Comment by pdaems** [comment]
@toorshia, I have tried to update my label using the new refresh function. However it doesn't visually update in the gauge.

failedGauge.refresh(1,10, {label:"new value"});

I will try to investigate it in the code myself

**Comment by toorshia** [comment]
I will investigate this..

**Comment by toorshia** [comment]
Yeah, turns out source contributor only assigned config to obj.config, but for changes to take effect, you need to assign properties to gauge properties, like obj.txtMax, or obj.txtLabel :)
Sorry, I totally missed this. That's what happens when you don't test.

**Comment by darkclaude** [comment]
Hello toorshia just give an example we dont understand what you mean
. for example if i want to change title after creating gauge already , write the full instruction code for us thank you

**Comment by MarcBradean** [comment]
Yes pls, how does this work?

**Comment by darkclaude** [comment]
he hasnt being active for 15days.........

**Comment by MarcBradean** [comment]
I just needed a way to change the title dynamically. So I simply added a new parameter to the refresh function called title and added these lines in the refresh function:
`  if(title && (typeof title =="string")){
	 obj.txtTitle.attr({"text":title});
  }
`
guess you could pretty much do this with any of them.

**Comment by NSchnitzler** [comment]
Accessing  the max value is working fine, but i don't understand how to change other properties dynamically.

**Comment by parismiguel** [comment]
Hello everybody!
Had any figure out how to update Customsectors? I'm trying to use the code provided here:

http://justgage.com/examples/custom-sectors.html

But the .update function is not working at all.

Thank you!

Paris

**Comment by toorshia** [comment]
Guys, as I said, update function is not really working at the moment. I will try to address this but cannot promise any dates, sorry.

In the meantime, use @MarcBradean method :)

**Comment by parismiguel** [comment]
Here's a workaround... I did it in a Wild West style... not fancy, but it works:

```html
<input id="gaugeValue" value="@ViewBag.GaugeValue" hidden />
                            <div id="gauge"></div>
                            <div style="text-align: center;">
                                <label style="padding-right:15px;">Bajo</label>
                                <input type="number" id="inpLow" name="Bajo" value="50" min="0" max="100" width="60" style="border-color:lightgray" />
                                <label style="padding-right:15px;padding-left:10px;">Alto</label>
                                <input type="number" id="inpHigh" name="Alto" value="95" min="0" max="100" width="60" style="border-color:lightgray" />
                                <input type="button" name="Actualizar" id="btnRefreshGauge" value="Actualizar" class="btn btn-primary btn-sm" />
                            </div>
```

```js
 var valgauge = $('#gaugeValue').val();
            var valLow = $('#inpLow').val();
            var valHigh = $('#inpHigh').val();

            var dflt = {
                min: 0,
                max: 100,
                symbol: '%',
                title: 'Servicios',
                pointer: true,
                pointerOptions: {
                    toplength: -15,
                    bottomlength: 10,
                    bottomwidth: 12,
                    color: '#8e8e93',
                    stroke: '#ffffff',
                    stroke_width: 3,
                    stroke_linecap: 'round'
                },
                gaugeWidthScale: 0.8,
                counter: true,
                label: "% nuevos"
            }


            var g = new JustGage({
                id: "gauge",
                value: valgauge,
                customSectors: [
                    {
                        color: "#00ff00",
                        lo: 0,
                        hi: valLow
                    }, {
                        color: "orange",
                        lo: valLow,
                        hi: valHigh
                    },
                {
                    color: "#ff0000",
                    lo: valHigh,
                    hi: 100
                }],
                defaults: dflt
            });

            $('#btnRefreshGauge').on('click', function () {
                valLow = $('#inpLow').val();
                valHigh = $('#inpHigh').val();
                valgauge = $('#gaugeValue').val();

                $('#gauge').html('');

               
                g = new JustGage({
                    id: "gauge",
                    value: valgauge,
                    customSectors: [
                        {
                            color: "#00ff00",
                            lo: 0,
                            hi: valLow
                        }, {
                            color: "orange",
                            lo: valLow,
                            hi: valHigh
                        },
                    {
                        color: "#ff0000",
                        lo: valHigh,
                        hi: 100
                    }],
                    defaults: dflt
                });
```

**Comment by suneetjain** [comment]
@MarcBradean The solution suggested by you worked for me. Thanks
