### ISSUE TITLE
Latest version not grabbed via Bower

### ISSUE THREAD

**Issue by Grayda** [toorshia/justgage#185]
When I try and grab JustGage via bower, it returns an older version which doesn't have `reverse`.

It might have something to do with newer versions not being tagged in the release. Can a new 'release' be made so people installing via bower can have the latest version?

**Comment by toorshia** [comment]
My bad :) Try now please. Thanks for pointing it out :)

**Comment by Grayda** [comment]
Works like a charm. Thanks for that :)
