### ISSUE TITLE
Problem to read a hi value of mysql

### ISSUE THREAD

**Issue by tresjo81** [toorshia/justgage#186]
Hello and happy new year.
the first thing is to thank you for your great work.
I have the following problem, I am reading data from sensors Arduino I previmente written in a MySQL database . proper operation until the number you insert more than 3 digits and one decimal. 999.9 ok,but1002.9 not working.
thanks

**Comment by tresjo81** [comment]
Can you help me?

**Comment by toorshia** [comment]
Hi, can you send me an example of the issue you're facing? Thanks :)

**Comment by tresjo81** [comment]
[sensores.txt](https://github.com/toorshia/justgage/files/77683/sensores.txt)
good night, the first thing is to thank you again.
I have attached the code for you to see as read data from the database.
operation www.meteoelche.tk/sensores.php you can see here, all values are read from aparen bd except pression. if I read for the pressure and the rest of values only works cuano is 999.9 or lower, if not superior load page being blank.

thanks

**Comment by toorshia** [comment]
Sorry, but I think it's something on your end. From what I can see on the example page you sent me, values over 999.9 work correctly (Presión atmosférica is 1234.3).

**Comment by tresjo81** [comment]
When I write the value manually, for example 1234.3 , proper operation but if I read from the database does not work then

**Comment by tresjo81** [comment]
I adjunt 3 captures.

1) pression 999,3 in a bd and work ok
2) pression 1007,3 in a bd and not work
3) table with a last values of bd

Thanks
![screenshot_2016-01-05-23-33-42](https://cloud.githubusercontent.com/assets/16510662/12129854/a47c3904-b406-11e5-9e59-87db156308a4.png)
![screenshot_2016-01-05-23-42-15](https://cloud.githubusercontent.com/assets/16510662/12129858/a9c30848-b406-11e5-94f2-81e2c7feefa5.png)
![screenshot_2016-01-05-23-42-36](https://cloud.githubusercontent.com/assets/16510662/12129863/ae274304-b406-11e5-9f6b-923da2a69a03.png)

**Comment by toorshia** [comment]
I just checked your file - your numbers are in wrong format - you have 1,004.5, and the correct input would be 1004.5. So you have to reformat values coming from database before feeding them to justGage.

**Comment by tresjo81** [comment]
if that was the problem , I have already solved . thank you very much
because I was going crazy . thanks
