### ISSUE TITLE
Enhancement: visualize a target range

### ISSUE THREAD

**Issue by NSchnitzler** [toorshia/justgage#187]
For some data it's useful to visualize a target range, not only by changing the odometer color. I imagine something like this:
![odo](https://cloud.githubusercontent.com/assets/6046936/12074456/7c8b1090-b155-11e5-94d6-56c354ccefbf.jpg)

**Comment by toorshia** [comment]
Mhm. I would try a slightly different visualisation, but the idea is sound :) Thanks

**Comment by asd31221** [comment]
I must have this feature.

**Comment by toorshia** [comment]
Watch #65
