### ISSUE TITLE
Donut doesn't accept min value different to 0

### ISSUE THREAD

**Issue by Pierre-Lannoy** [toorshia/justgage#188]
Hi Bojan!
Once again, I don't know if I'm facing a bug or if this is a misunderstanding on my part. So sorry if this question/report is "unfounded".

When i set a min value which is not equal to 0, when using gauge in "donut" mode, the drawing is buggy...
Here is a test you can view: http://wp-dev.lannoy.fr/wp-content/plugins/live-weather-station/test/justgage.html
Is it normal (i.e. donut must be used with a min value equal to 0) or is it a bug?

**Comment by toorshia** [comment]
Hi Pierre,

Donut is by design to be used with a min value of 0. Otherwise, in my opinion, it wouldn't really make sense, visually :) Thanks!

**Comment by Pierre-Lannoy** [comment]
You're right, it makes sense... :)
Thanks for your answer.
