### ISSUE TITLE
Possible to have a different fill value and text value?

### ISSUE THREAD

**Issue by boldmovecreative** [toorshia/justgage#191]
I would like to use this library to display a custom percentage value in the middle, but also have a separate value option that controls the fill amount.

Ideally something like this using custom sectors:
![Example gauge](http://i.imgur.com/wNgHR1X.png)

Any pointers or tips would be amazing. Thank you for this great library.

**Comment by toorshia** [comment]
Sorry, missed this one. Did you find a way to achieve desired effect? :)

**Comment by boldmovecreative** [comment]
I did with textRenderer. Apologies I had passed up that option in the source.

**Comment by toorshia** [comment]
Awesome :)
