### ISSUE TITLE
Formatting minimum and maximum values with commas AND dollar signs?

### ISSUE THREAD

**Issue by boldmovecreative** [toorshia/justgage#193]
Would love to see an option that allows the minimum and value options to be rendered with a currency format.

**Comment by toorshia** [comment]
Yeah, that makes sense. Will implement it :)

**Comment by LucasRosa90** [comment]
Instead of just currency, I guess is better implement a label to min and max value.

**Comment by boldmovecreative** [comment]
@LucasRosa90 For now I've customized the library to add the dollar sign but you're right. Prepend and append options for values make sense that way it's not limited to currencies.

@toorshia Thoughts?

**Comment by toorshia** [comment]
I think the best option would be to provide custom text renderer function for all texts (min, max, value, label...)
