### ISSUE TITLE
If value option is greater than max option custom sector coloring reverts to default red hex color.

### ISSUE THREAD

**Issue by boldmovecreative** [toorshia/justgage#194]
And for display purposes we cannot get away with making the value and max equal because of the way we are using this library (see below).

![Image](http://i.imgur.com/fHUJ9HG.png)

Here's the generated JavaScript behind the one with 132%. The gauge fill should be green.

```
var gauge_one = new JustGage({
	
	id : "gauge_one",
	value : 15176,
	min : 0,
	max : 11521,
	title : "2015 Pump Bookings",
	label : "$15,176",
	textRenderer : function() {
		return "132%"
	},
	
	titleFontColor : "#141414",
	titleFontFamily : "GTPressuraWeb",
	titlePosition : "below",
	titleFontColor : "#141414",
	valueFontFamily : "Open Sans",
	valueMinFontSize : 14,
	titleMinFontSize : 14,
	labelMinFontSize : 14,
	minLabelMinFontSize : 14,
	maxLabelMinFontSize : 14,
	
	hideInnerShadow : true,
	levelColorsGradient : false,
	counter : true,
	
	customSectors : [{
		color : "#e6281e",
		lo : 0,
		hi : 8526,
	}, {
		color : "#f6f400",
		lo : 8527,
		hi : 11520,
	}, {
		color : "#94d61c",
		lo : 11521,
		hi : 15177,
	}],
});
```
							
Any thought on this would be appreciated. Thank you.

**Comment by toorshia** [comment]
I think there's a bug in getColor(). Whenever you set value to match lo value for the sector, it returns red. Let me do some fixing...

**Comment by toorshia** [comment]
Fixed. Check http://justgage.com/issues/194.html, and get latest commit. Thanks for the heads-up!
