### ISSUE TITLE
Gauge that shows two values..

### ISSUE THREAD

**Issue by stuartaw** [toorshia/justgage#199]
I can think of a couple of ways of implementing, however one feature that would great for more than a few uses is two allow for two incoming values, and perhaps a separator.

By which I mean, for example a sports game score, the two values would be team1score, team2score
The gauge would run 0..(team1score+team2score), the indicator at team1score, and the gauge value would be team1score<separator>team2score (for example 13-26 ).

This could be done with a setting that told the system to interpret the max value as value2, or detect the setting of a value2? I started hacking one up but thought it could be more generically useful than just me.

This would make this great little control usable for many situations where you are gauging comparative numbers.

Make some sense? Hopefully, I think it would be a great enhancement!

**Comment by toorshia** [comment]
Interesting. Can you give me a visual example of such usage? Would be much easier for me to understand :) Thanks!

**Comment by stuartaw** [comment]
Of course, my description is not great I know. Here is something I just cut/pasted together.
I may have a hack at it today, I think it could look quite good.
For space purposes I am also thinking of an optio to move the text to 'below' the guage (although I prefer inside where it fits)

![guages](https://cloud.githubusercontent.com/assets/12621668/13036675/5931e7b4-d3d2-11e5-8443-ffbd1b5909f2.jpg)

**Comment by toorshia** [comment]
You can use textRenderer function to achieve this :)

**Comment by stuartaw** [comment]
I actually gave that quite a try before I gave up (which is a pity, lack of time). any chance of an example that uses 2 input values? thank you.

**Comment by toorshia** [comment]
http://justgage.com/examples/text-renderer-2.html
