### ISSUE TITLE
Further control over labels, colours,fonts and adornments

### ISSUE THREAD

**Issue by brendanheyu** [toorshia/justgage#2]
:)

Could I have more control over what is displayed in the UI?

I would love to be able to set or remove each label/string. Having just the vector arc is a very attractive prospect.

Setting the colour of each label/string is also a big want.

Setting an adornment for each string is also attractive (might be a "%" or a "$", eg 76% or $99 or 173°)

I'll keep on thinking!

**Comment by sangeetash** [comment]
Hi Toorshia,

My requirement is to show different colors in same gauge. Like 0-60 % = green, 60-70 = red, 70-80 = yellow and rest transparent.

Can I do it with JustGage using customSectors?
I tried but it is not working. DO I need to update JustGage.js? If yes please help me in updating it.

**Comment by toorshia** [comment]
Hi,

At the moment - no, you can't. I will consider this option in future. Thanks.

**Comment by simonl65** [comment]
Hi Toorshia,

Many thanks for justGage - it's excellent!

I can't seem to find an option for changing the color of the "min" and "max" labels - is it possible?

Cheers,
Simon

**Comment by toorshia** [comment]
You can't change min / max colors at the moment.

**Comment by simonl65** [comment]
OK, no problem - I can get around that by changing the background colour. Thanks for your swift response.

**Comment by prakasamm** [comment]
You can change this as following ways also

```javascript
    var GageTwo = new JustGage({
        id: 'GageTwo',
        value: 80,
        min: 0,
        max: 100,
        reverse: true,
        relativeGaugeSize: true,
        counter: true,
        valueFontColor: "#00B1FF",
        valueFontFamily: "Lato"
    });
    
    GageTwo.txtValue.attr({
        "font-weight": "300"
    });
```
