### ISSUE TITLE
Problem with refresh Gage (decimals)

### ISSUE THREAD

**Issue by arubia45** [toorshia/justgage#200]
Hello, I have some problem when I refresh with decimals:

   ```
   var gg1 = new JustGage({
        id: "gg1",
        formatNumber: true,
		gaugeWidthScale: 0.6,
        counter: true,
		pointer: true,
		title: 'Máximo ºC'
      });
```

`gg1.refresh(5,8)`

Any ideas? thanks

**Comment by toorshia** [comment]
Try inputing 5.8 (dot instead of comma for decimals).

**Comment by arubia45** [comment]
Sorry, 

gg1.refresh(5.8)

neither

**Comment by arubia45** [comment]
Hello, if I create the gaug:

` <div id="minima" class="gauge" data-value="4.5" data-min="-10" data-max="50" data-gaugeWidthScale="0.6"></div>`

Ok, but when I refresh:

` maxima.refresh(19.5);`

Not work.

![gaug](https://cloud.githubusercontent.com/assets/17407698/13229238/3092791c-d9a0-11e5-9a21-2091d52d99ff.png)

**Comment by toorshia** [comment]
Try setting decimals parameter (decimals=2). Check examples.

**Comment by arubia45** [comment]
ok perfect.

Thanks
