### ISSUE TITLE
how to use justgage as result of calculation

### ISSUE THREAD

**Issue by hgestel** [toorshia/justgage#201]
I use now :
varOwnUse.txtValue.node.textContent = (parseInt(varSolarWattTotal.txtValue.node.textContent) - parseInt(varSolarDeliverTotal.txtValue.node.textContent) + parseInt(varElectraConsumedTotal.txtValue.node.textContent));
to create an new justgage **Own_use**. it is only chowing the calculated number not the grafical presentation
Is this the way to get a calculated new justgage ?

**Comment by toorshia** [comment]
Well, I guess you have to make a call to justGage() function, and specify input parameters like id of element you are rendering your gauge into, and of course, the value you are intending to display. Optionally, you can set other parameters. Check examples to understand better how to use it.
