### ISSUE TITLE
corrupted file http://justgage.com/justgage-1.2.2.zip

### ISSUE THREAD

**Issue by danielsawan** [toorshia/justgage#203]
I think the zip (http://justgage.com/justgage-1.2.2.zip) on the main page http://justgage.com/ is corrupted.
Both js at the root of the zip seems to be empty

**Comment by danielsawan** [comment]
Can't extract them on Windows 10

**Comment by toorshia** [comment]
Hi, just tried downloading and extracting (OSX), seems everything works fine?

**Comment by danielsawan** [comment]
do you tried to open the js file after the extraction ?

**Comment by toorshia** [comment]
Yep. Just now. Examples work as well.

**Comment by danielsawan** [comment]
It is corrupted on my Windows. I also send the link to a friend who also have windows to confirm and he has the exact same problem.

This file seems to be corrupted on Windows.

**Comment by elebumm** [comment]
I am having the same problem @danielsawan. I am also using Windows 10 and getting an error trying to extract. I am using winrar to extract if that helps. (paid copy of course)

**Comment by Ciao121** [comment]
Here's the same...

**Comment by toorshia** [comment]
OK, I just repacked and uploaded. Can you try now?

**Comment by danielsawan** [comment]
same problem :/

**Comment by toorshia** [comment]
Hm. Try now, please, don't have win machine by me right now.

**Comment by danielsawan** [comment]
Now it work but the packaging contain some macos folder : http://puu.sh/nwPzp/3894b3d2bb.png

**Comment by toorshia** [comment]
One more time, please :)

**Comment by danielsawan** [comment]
Yes it is ok now :)

**Comment by toorshia** [comment]
Awesome. Thanks ;)
