### ISSUE TITLE
How to change dynamicaly min or max value ? 

### ISSUE THREAD

**Issue by Jugulaire** [toorshia/justgage#204]
I making a live dashboard with JustGage but i cannot find how to edit the min or max value dynamicaly like we can with value. 
Anybody can help me ?

**Comment by toorshia** [comment]
You can update max by calling object.refresh(new_value, new_maximum);
One of these days I'll make a prototype.update() function where you'll be able to update every parameter.

**Comment by noeldum** [comment]
+1 interest in  the prototype.update().
