### ISSUE TITLE
Ability to change the angle of the entire gage.

### ISSUE THREAD

**Issue by JamesJGarner** [toorshia/justgage#205]
This is how it looks at the moment 
![image](https://cloud.githubusercontent.com/assets/4941923/13598960/a625eda2-e518-11e5-942b-6823ad7ef258.png)

Is it possible to make it look like this?
![image](https://cloud.githubusercontent.com/assets/4941923/13598936/8c2acf9e-e518-11e5-8f9d-df0c87a88c2d.png)

Thanks,

James

**Comment by toorshia** [comment]
Hi, 

Check #18.
