### ISSUE TITLE
npm outdated

### ISSUE THREAD

**Issue by rvanmil** [toorshia/justgage#211]
Can you publish the latest version to npm?

**Comment by tomasklingen** [comment]
The release on cdnjs as well. 14 commits since 1.2.2. atm.

**Comment by andretf** [comment]
Current npm version (1.2.2) is not working on Chrome 53 with me, it was working on Chrome 52. It isn't rendering SVG.

I had to get direct from here:

    "justgage": "toorshia/justgage"

**Comment by bmcgonag** [comment]
Still looking to get an update for NPM.  Any word on that?
