### ISSUE TITLE
Update value after jQuery/Ajax call

### ISSUE THREAD

**Issue by dade80vr** [toorshia/justgage#212]
Hi. It is possible to refresh value like this?
`$("#gauge").JustGage({value: newvalue})`

Because i create a NEW gauge on load using a custom function (i have got 20 gauges with same opts)
`function createGauge(id,value,opt) { var g = new JustGage({ ............. }) }`

But when i make the Ajax call i cannot recall "createGauge" because "new" will create a clone!!!!
And i cannot use `g.refresh(value)` because "g" is not defined into Ajax function.

Now i'm emptying container div via jQuery, but gauge is re-created everytime and not updated..

How could i do?
Thanks!

**Comment by dade80vr** [comment]
Declared "g" as global var.. 
Now it's working with "svg" check:

`var g;
if ($("#"+id).has("svg").length) {
	g.refresh(value);
}else{
	g = new JustGage({..... })
}`

But, how could i simplifly the code?

**Comment by kentonbmax** [comment]
I am having a similar issue with the value updating when rendering from an angular component, within a document ready function. This was working in previous version. 

![image](https://cloud.githubusercontent.com/assets/15804484/14680194/6cf5a664-06ea-11e6-8c48-45de8f7119b7.png)

**Comment by kentonbmax** [comment]
I rolled back to the version targeted on http://justgage.com/ and my issue is resolved.

**Comment by dade80vr** [comment]
@kentonbmax how did you solve the problem?

**Comment by kentonbmax** [comment]
I rolled back to Raphael 2.1.0, but there is an SVG issue, so you will get errors on console. But in my case it still works.

**Comment by toorshia** [comment]
Closing as it is Raphael version related issue. Please use Raphael 2.1.x for now.
