### ISSUE TITLE
Leading digits

### ISSUE THREAD

**Issue by kitecom** [toorshia/justgage#214]
Possible to have leading zeros?
I would like to the counter to run from 00000 to 10000, butwould like to see (for example), 00259. 01830 etc 
Thanks

**Comment by toorshia** [comment]
Yes, use textRenderer parameter to supply custom function for displaying value.

**Comment by kitecom** [comment]
Thanks - could you give me an example?

**Comment by toorshia** [comment]
http://justgage.com/examples/custom-value-renderer.html
