### ISSUE TITLE
"value" and "label" disappearing after "mouse hover"  event in IE11

### ISSUE THREAD

**Issue by AK1979** [toorshia/justgage#215]
Hi , 

In IE11 the "value" and "label" disappearing after "mouse hover"  event.

Maybe it's related to the last change ?  callback function after gauge animation ends .

Thanks

**Comment by AK1979** [comment]
It only happens when the relativeGaugeSize = true …

**Comment by toorshia** [comment]
Just tested on IE11. Relative gauge size feature is nor working, but I could not reproduce disappearing labels on mouse over event.
