### ISSUE TITLE
How to change the Title,Value,Lable font-size?

### ISSUE THREAD

**Issue by amitshahc** [toorshia/justgage#225]
I tried using 
titleFontSize: "1em", titleFontSize: 12, titleFontSize: "12px"
none of them working.

**Comment by brunotourinho** [comment]
same problem here!

**Comment by amitshahc** [comment]
@brunotourinho you can use [this ](http://stackoverflow.com/questions/37673917/justgage-js-change-title-value-label-font-size/37692651#37692651) solution temporarily.

**Comment by brunotourinho** [comment]
Thank you @amitshahc !!!

**Comment by toorshia** [comment]
I will add font options for all texts in a week or two, hopefully :)

**Comment by sarkariajatt** [comment]
Hi,
i am having an issue with the font-weight. As i can see that all other font on my application is having font-weight:normal. But when i try to set the same thing on the label it doesn't show any impact on the font weight. The font-weight looks like it is around 600. How can i make the label or value to the same size like the font we have in the comment box. What i want is font like = This but in gauge it is coming like ## This
