### ISSUE TITLE
TypeScript .d.ts definitions available? 

### ISSUE THREAD

**Issue by daixtrose** [toorshia/justgage#227]
Are there any [Typings definitions](https://github.com/typings/typings) available for justgage?

**Comment by tomasklingen** [comment]
Nope. To at least satisfy tsc / IDE I created a smal. d.ts that has only this:

```
declare interface JustGage {
    refresh(val: any, max?: any, config?: any);
}

declare module "justgage" {
    export let JustGage: JustGage;
}
```

And then `import {JustGage} from "justgage";`

I only needed the constructor and refresh().

**Comment by thiboot** [comment]
Hi, @tomasklingen 
I'm facing issues with your solution.

Import is ok but when i call the **constructor**:
>[ts]
> Cannot use 'new' with an expression whose type lacks a call or construct signature.
> import JustGage

When i call **refresh**:
> [ts] 
> Property 'refresh' does not exist on type '{}'.
> any

My code:
```typescript
this._BMP180GaugePressureOptions = new JustGage({
      id: "pression",
      value: 960,
      valueFontColor: AppSettings.COLOR_LIGHT,
      min: 960,
      max: 1070,
      title: "Atmospheric pressure",
      titleFontColor: AppSettings.COLOR_PRIMARY,
      label: "hPa",
      gaugeWidthScale: 0.3,
      gaugeColor: 'rgba(6, 26, 51, 0.9)',
      labelFontColor: AppSettings.COLOR_PRIMARY,
      levelColors: ["#0040FF", "#1E74FF", "#35A6FF", "#45D4FF", "#4BFFFF"]
    });
```

```typescript
this._BMP180GaugePressureOptions.refresh(Number(x.body[0].pressure)/100);
```

I wouldlike to use **txtTitle.attr** too:
```typescript
this._BMP180GaugePressureOptions.txtTitle.attr({
      "font-size": "16px",
      "font-weight": "bold",
      "font-family": "Arial",
      "fill": AppSettings.COLOR_PRIMARY,
      "fill-opacity": "1"
    });
```

**Comment by toorshia** [comment]
Sorry guys, I can't really support the library itself + different integrations, I'm pretty much alone in this and already loosing my marbles all over the place. However, if someone is willing to take care of this, I'll be glad to welcome them aboard :)

**Comment by LarsKemmann** [comment]
@thiboot -- I fixed it as follows:

```typescript
declare interface JustGage {
  new (options: any): JustGage;
  refresh(val: any, max?: any, config?: any);
}
```
