### ISSUE TITLE
How can i add vale in points (10.5)

### ISSUE THREAD

**Issue by MuhammadAzad** [toorshia/justgage#228]
Hi,

Nice library and script i am using it on my company intranet web, can you please guide me how can i add value in points (10.5).

Thanks & Regards,

**Comment by beisert1** [comment]
@MuhammadAzad same problem here

**Comment by beisert1** [comment]
Figured it out! Change the value to however many digits passed number you want to display.

![image](https://cloud.githubusercontent.com/assets/6433253/17713180/8d58b060-63c7-11e6-8a17-548f1fa2226b.png)
