### ISSUE TITLE
Different scales for different sections

### ISSUE THREAD

**Issue by caboose014** [toorshia/justgage#230]
I am going to try to explain what I mean, sorry - I am not the best at this.

I am looking for the following functionality for use in displaying electrical values. Similar to your humanfriendly readings, power readings go though different ranges, for example watt readings are between 0 and 999, where kilowatt readings are 1000+.

I would like to use the same gage for all my readings and have the ranges the same - so you can easily see which gage is displaying more ( rather than each gage having a different scale). Each section of the gage could have a different scale to it.

Lets take a gage with a min of 0 and a max of 50,000 and say its split into 9 sections: 

- Section 1 from 0-50
- Section 2 from 51-100
- Section 3 101-200
- Section 4 201-500
- Section 5 501-1,000
- Section 6 1,001-2,000
- Section 7 2,001-5,000
- Section 8 5,0001-10,000
- Section 9 10,001-50,000

But have the ability to define the sections, and their scale/range in number values.

Similar to the image here: 
![img_0048](https://cloud.githubusercontent.com/assets/5124349/17233836/9286f0ae-5587-11e6-8ec6-90b49bf4c9d1.jpg)

-edit-
After some research, I am after a logarithmic gage!

**Comment by toorshia** [comment]
That's a cool feature :) I'd have to rewrite the whole damn thing to achieve this, and frankly, I am not even clear at this moment how would I actually do it. Perhaps, one day. Thanks :)
