### ISSUE TITLE
Gauge.refresh() not working as expected

### ISSUE THREAD

**Issue by creightons** [toorshia/justgage#231]
The March 29, 2016 allowed the refresh function to update the gauge's config options. I expected that updating the config with new options would cause the gauge to change, such as changing the label or the title. However, as can be seen in the fiddle in the link below, this isn't happening. Am I mistaken about how refresh is supposed to work, or does it only modify the current value and the maximum value of the gauge?

https://jsfiddle.net/oazoqvoy/5/

**Comment by toorshia** [comment]
Please refer to #241
