### ISSUE TITLE
Donut not rendering correctly if range starts negative.

### ISSUE THREAD

**Issue by dceejay** [toorshia/justgage#232]
If a donut is specified with min value < 0 then rendering goes awry...

![image](https://cloud.githubusercontent.com/assets/5375409/17407964/305a8376-5a61-11e6-97e5-e82b6c22cc8a.png)

![image](https://cloud.githubusercontent.com/assets/5375409/17407976/3ab606ba-5a61-11e6-95ac-d864d597c55e.png)

**Comment by toorshia** [comment]
Sorry, negative values are not supported yet.

**Comment by dceejay** [comment]
so - why not leave this open as a reminder of "things to do" ? - or is there a list elsewhere it should be added ?

**Comment by toorshia** [comment]
Makes sense, watch #248

**Comment by dceejay** [comment]
Thanks.
