### ISSUE TITLE
How i can remove the scrolling toolbar

### ISSUE THREAD

**Issue by cjdg** [toorshia/justgage#233]
Hi im having a small issue while using justgage on chrome based browsers, cant remove the scrollbar, but firefox, and opera doesnt have scrollbars
![seleccion_007](https://cloud.githubusercontent.com/assets/5726836/17420918/7f7e82fe-5a6b-11e6-8ef5-0f2ffb945563.png)

**Comment by toorshia** [comment]
Hi, I don't think this is justGage related issue. Check this example to test: http://justgage.com/examples/reverse.html
