### ISSUE TITLE
Gauge Fails to render when put it hidden box

### ISSUE THREAD

**Issue by neoyagami** [toorshia/justgage#234]
If the gauge is rendered offscreen (in a hidden div or hidden tab) the gauge fails to render and raphael send this error

![captura de pantalla 2016-08-10 a las 9 32 03 a m](https://cloud.githubusercontent.com/assets/3663321/17555385/6b578a8e-5edd-11e6-8b70-f225335b81c0.png)

and in the box where the gauge will be added shows some dark lines
![captura de pantalla 2016-08-10 a las 9 33 05 a m](https://cloud.githubusercontent.com/assets/3663321/17555414/8314b0ac-5edd-11e6-92ec-58017befa414.png)

**Comment by toorshia** [comment]
It works, as long as you set width and height of the element containing gauge object.
