### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by beisert1** [toorshia/justgage#235]
I am currently working on a dashboard project utilizing cefsharp embedded in winforms using c#. I am using google chart api and justgage to create charts.

Problem is I am using wkhtmltopdf to convert the html file to a pdf file for exporting and the justgage gauges will not export to pdf. Is it possible to convert the gauges to an image file for pdf exporting?

**Comment by beisert1** [comment]
Similar to google charts way of converting to image. 

`chart.getChart().getImageURI()`

**Comment by beisert1** [comment]
Closed.

I am going to attempt using an SVG to PNG to PDF or something similar.

Thanks.

**Comment by altjx** [comment]
@beisert1,

Did you ever get this resolved?
