### ISSUE TITLE
Can I disable any animations?

### ISSUE THREAD

**Issue by daixtrose** [toorshia/justgage#237]
I use justgage in an Ionic2/Angular2 context and encounter strange behaviour with animation times and update intervals interfering and leading to spurious flicker.

In order to make sure animation is not the culprit i would like to turn it off completely, How?

[Here's a plunkr](http://plnkr.co/edit/KTNtzvBSWC64hOxTRZUV?p=preview) showing how I use it, but unfortunately only the Ionic 2 app shows the flicker.

**Comment by beisert1** [comment]
Put 0 for both of these values to disable animations.

![image](https://cloud.githubusercontent.com/assets/6433253/17714344/545662a2-63cd-11e6-8fe5-b284494fb1a7.png)

**Comment by daixtrose** [comment]
Thanks. Unfortunately the problem  is elsewhere. Closing since question was answered.
