### ISSUE TITLE
Display symbol after min and max values

### ISSUE THREAD

**Issue by beisert1** [toorshia/justgage#239]
I want to display a '%' symbol after each min and max value, any suggestions would be greatly appreciated. Thanks.

![image](https://cloud.githubusercontent.com/assets/6433253/17741242/7e9c7c3a-6469-11e6-87a0-1c721d82915f.png)

**Comment by hollyewhite** [comment]
I'd love to know how to do this as well. I tried to append it in the JS but didn't have much luck.

**Comment by ikonikre** [comment]
You can use the `minTxt` and `maxTxt` options. For example, to set the option `minTxt: "$0"` will render '$0' in place of the value set for `min`.

![minTxt snapshot](https://cloud.githubusercontent.com/assets/1932157/18468454/0fa12aec-7972-11e6-8e11-fccda84d17d1.png)
