### ISSUE TITLE
title is not displayed

### ISSUE THREAD

**Issue by luohuaming** [toorshia/justgage#250]
This is a great project,but title is not displayed. Can you help me?thank you.
http://gpxscan.com/gpxgooglemap_v2.jsp?gpx=demotrack&share=share

**Comment by toorshia** [comment]
I removed title couple of days ago due to many requests. I will think about reintroducing it as an optional parameter, but for now, it is what it is :) thanks

**Comment by undeflabs** [comment]
I think the title was a quite handy thing to include a title, now it is much more code to do. I would like to have a title as an optional parameter back again. =)
