### ISSUE TITLE
getColor doesn't work properly after range support

### ISSUE THREAD

**Issue by Deklin** [toorshia/justgage#251]
```
function getColor(val, pct, col, noGradient, custSec) {

  var no, inc, colors, percentage, rval, gval, bval, lower, upper, range, rangePct, pctLower, pctUpper, color;
  var noGradient = noGradient || custSec.length > 0;

  if (custSec.length > 0) {
    if (custSec.percents === true) val = pct * 100;
    for (var i = 0; i < custSec.ranges.length; i++) {
      if (val >= custSec.ranges[i].lo && val <= custSec.ranges[i].hi) {
        return custSec.ranges[i].color;
      }
    }
  }
```

Note that the first check is custSec.length > 0, however this was true before when custSec was an array, now it is moved into ranges so this check (and the no gradient check) seems invalid now.

**Comment by andrepaulo** [comment]
if you add a .length it will work

`customSectors: {
          length: 1,
          ranges: [{
            color: "#43bf58",
            lo: 0,
            hi: 70
          }, {
            color: "#ff3b30",
            lo: 71,
            hi: 100
          }]
        }`

**Comment by Steveee79** [comment]
hi,

andrepaulo solution is not the right way to go instead
just replace this line
from:
`  if (custSec.length > 0) {
`

to:
`  if (typeof custSec.ranges == 'object' && custSec.ranges.length > 0) {
`

**Comment by andrepaulo** [comment]
@Steveee79, my solution was given only to avoid changing the original justgage.js , only passing length as an attribute with value 1 will make the functionality work, while it's not fixed. But I agree this way is more accurate, you should propose a Pull Request. ;) Cheers!

**Comment by 3301x2** [comment]
None of this solutions are working for me, any other fix?

**Comment by robertsLando** [comment]
@3301x2 Which version are you using?

**Comment by robertsLando** [comment]
@3301x2 This has been fixed 

```js
function getColor(val, pct, col, noGradient, custSec) {

    var no, inc, colors, percentage, rval, gval, bval, lower, upper, range, rangePct, pctLower, pctUpper, color;
    var cust = custSec && custSec.ranges && custSec.ranges.length > 0;
    var noGradient = noGradient || cust;

    if (cust) {
      if (custSec.percents === true) val = pct * 100;
      for (var i = 0; i < custSec.ranges.length; i++) {
        if (val >= custSec.ranges[i].lo && val <= custSec.ranges[i].hi) {
          return custSec.ranges[i].color;
        }
      }
    }
...
```

**Comment by 3301x2** [comment]
> @3301x2 This has been fixed
> 
> ```js
> function getColor(val, pct, col, noGradient, custSec) {
> 
>     var no, inc, colors, percentage, rval, gval, bval, lower, upper, range, rangePct, pctLower, pctUpper, color;
>     var cust = custSec && custSec.ranges && custSec.ranges.length > 0;
>     var noGradient = noGradient || cust;
> 
>     if (cust) {
>       if (custSec.percents === true) val = pct * 100;
>       for (var i = 0; i < custSec.ranges.length; i++) {
>         if (val >= custSec.ranges[i].lo && val <= custSec.ranges[i].hi) {
>           return custSec.ranges[i].color;
>         }
>       }
>     }
> ...
> ```

This worked like a charm.

**Comment by robertsLando** [comment]
@3301x2 YOu should not fix the code but just use the latest version you find here. It has many fixes inside!
