### ISSUE TITLE
Reverse.html - example throws uncaught type error.

### ISSUE THREAD

**Issue by JustAGuyTryingToCodeSomething** [toorshia/justgage#258]
justgage.js:1016 Uncaught TypeError: Cannot read property 'length' of undefined(…)

Gauge created with:

customSectors: [{
          color: '#ff0000',
          lo: 50,
          hi: 100
        }, {
          color: '#00ff00',
          lo: 0,
          hi: 50
        }],
        counter: true
      });

Should be ranges: []

**Comment by Steveee79** [comment]
hi,

just replace this line
from:
`  if (custSec.length > 0) {
`

to:
`  if (typeof custSec.ranges == 'object' && custSec.ranges.length > 0) {
`
