### ISSUE TITLE
Long term refresh & memory leak

### ISSUE THREAD

**Issue by synologic** [toorshia/justgage#269]
Hi all,

i'm using several justgages on a monitoring page, with justgages updated every second via the .refresh function.

If i keep the page open in Chrome for a few hours, the page crashes with out of memory. If i remove the gages there's no error. I did a profile in chrome and at least, for a few minutes of usage, there's no leak.

Any suggestions ?

**Comment by mariobrizuela** [comment]
Same problem here, 9 gages in a page, refresh rates of 1 second or less are quickly worsening the situation.  Also cpu usage is climbing up to 98% in a core i7 with just one chrome window open showing 9 gages at 500msec refresh rate.

**Comment by mariobrizuela** [comment]
Somebody can help with this problem? It turns Justgage unusable for long term monitoring applications.

**Comment by toorshia** [comment]
Hi guys, thanks for the feedback.
I did make some effort a while ago regarding this, and came to conclusion that there was no memory leak after couple minutes of profiling. If someone more experienced in these matters can chime in, I' d be more than happy to tag along and make necessary changes to the code.

**Comment by synologic** [comment]
Yeah it's tricky, short term profiling shows no memory leaks here either ... this will be a tricky one

**Comment by mariobrizuela** [comment]
Haven´t done any profiling yet, but I found something that can give you a clue. When I set refreshAnimationTime = 0 the memory leak seems to disapear. Maybe trying a profiling with long refreshAnimationTime?

**Comment by synologic** [comment]
Looks like this problem is related to Raphael and not Justgage. I'm using the latest RaphaelJS but the problem persists, and i have found quite a few issues with Raphael and path animation just searching on Google. Will do some deeper investigation.

**Comment by woodev01** [comment]
Related to what @mariobrizuela said, is your refreshAnimationTime longer than your refresh rate? If it is, it might be keeping a hold of all the calls to the refresh animation adding more and more memory as more calls happen than resolutions.

**Comment by synologic** [comment]
For me, even with refresh anim timer set to 0, after a few hours, same problem. Ended up using something else, it's not as pretty but oh well :(

**Comment by amlrJan2015** [comment]
I was able to eliminate the problem as far as possible by switching off shading.
"hideInnerShadow: true" in config.
Optional(justgage.js):
`if(!obj.config.hideInnerShadow) {
      if (ie != null && ie < 9) {
          // VML mode - no SVG & SVG filter support
      } else if (ie != null) {
          onCreateElementNsReady(function () {
              obj.generateShadow(svg, defs);
          });
      } else {
          obj.generateShadow(svg, defs);
      }
  }`

**Comment by robertsLando** [comment]
I suggest to stop refreshing gauges when page runs on background. 

```js
$(window).blur(function(){ 
window.disableRefresh = true;
})

$(window).focus(function(){ 
window.disableRefresh = false;
})
```
