### ISSUE TITLE
noGradient not working

### ISSUE THREAD

**Issue by byedma** [toorshia/justgage#270]
Hello,

I want static colors, no gradient, i have it as follows in controller.
` $scope.noGradient = true;
                $scope.customSectorsBMI= {
                    ranges: [
                        {
                            color: '#fff600',
                            lo: 0,
                            hi: 18.5
                        },
                        {
                            color: '#00ff00',
                            lo: 18.5,
                            hi: 25
                        },
                        {
                            color: '#ff0000',
                            lo: 25,
                            hi: 50
                        }]
                };`
               

in HTML, I have 

`
            <div justgage title="BMI" value="{{bmi}}" min="0" max="50" label="BMI" no-gradient="{{noGradient}}" 
                 custom-sectors="{{customSectorsBMI}}" decimals="0" humanFriendlyDecimal="2" humanFriendly="true"></div> `

In this example, for value 23, it should show color, #00ff00. It shows orange.

**Comment by Bandit-PsyH** [comment]
Find "function getColor(val,..." in justgage.js and replace 
from
if (custSec.length > 0) 
to
(custSec.ranges.length > 0)

**Comment by robertsLando** [comment]
Fixed
