### ISSUE TITLE
Donut not well rendered during animation

### ISSUE THREAD

**Issue by Thiktak** [toorshia/justgage#276]
Hello,

When i render the gauge in **donut** mode, with value ``donut: "true"`` (string), the gauge is well rendered ... but the animation is shifted during the animation.
No issue if the parameter is a boolean.

See in action: https://jsfiddle.net/Thiktak/5j2zmmg7/

![gauge](https://cloud.githubusercontent.com/assets/1201486/23529602/804f8736-ff9e-11e6-9648-7a1730d588e6.png)

**Comment by kuanyen** [comment]
I also encounter this issue, but it seems to be solved in latest justgage. I guess this issue can be closed?
