### ISSUE TITLE
Custom Sector problem

### ISSUE THREAD

**Issue by brothman01** [toorshia/justgage#279]
Hi, I am trying to use the justgage in an OOP PHP function.

```
	public function gauge_cell( $title, $gauge_class, $value, $max ) {

				return '<div class="onequarter cell">

					<div id="' . $gauge_class . '" class="gauge"></div>
						<script>
							var g1;
							document.addEventListener( "DOMContentLoaded", function( event ) {
								var g1 = new JustGage( {
									id: "' . $gauge_class . '",
									value: ' . $value . ',
									min: 0,
									max: ' . $max . ',
									title: "' . $title . '",

									customSectors: {
								  percents: true,
								  ranges: [{
								    color : "#FF0000",
								    lo : 0,
								    hi : 50
								  },{
								    color : "#00FF00",
								    lo : 51,
								    hi : 100
								  }]
								}

									} );
							} );
						</script>

				</div>';

	}
```

as you can see I tried to used custom sectors in my function.  This function can be used to correctly print out functional justgages without the customSectors code (if you remove that part and the rest works fine) but when I try to use the custom sectors feature the browser prints an empty space where the justgage should be.  What is wrong with how I am using the justgages?

(Yes, I did return it to an echo, the mechanism for content appearing on the page is not the problem)

**Comment by BarryCarlyon** [comment]
Try applying this open PR request to JustGauge and see if that fixes your problem: https://github.com/toorshia/justgage/pull/278

**Comment by brothman01** [comment]
well that helped but it still does not work.  Now I can add the custom sectors code but it prints out the original gauages (without the custom sectors applied)

**Comment by brothman01** [comment]
that PR did not work.  The color I set is not affecting the gauges (I used black to test):

						<script>
							var g1;
							document.addEventListener( "DOMContentLoaded", function( event ) {
								var g1 = new JustGage( {
									id: "' . $gauge_class . '",
									value: ' . $value . ',
									min: 0,
									max: ' . $max . ',
									title: "' . $title . '",
									gaugeWidthScale: 0.6,
									customSectors: {
										percents: true,
										ranges: [{
											color : "#000000",
											lo : 0,
											hi : 50
										},{
											color : "#000000",
											lo : 51,
											hi : 100
										}]
									},
									counter: true
									});

							} );
						</script>

**Comment by brothman01** [comment]
I got it to work (I was just trying to reverse the colors) using this code:
						<script>
							var g1;
							document.addEventListener( "DOMContentLoaded", function( event ) {
								var g1 = new JustGage( {
									id: "' . $gauge_class . '",
									value: ' . $value . ',
									min: 0,
									max: ' . $max . ',
									title: "' . $title . '",
									gaugeWidthScale: 0.6,
									customSectors: {
										percents: true,
										ranges: [{
											color : "#000000",
											lo : 0,
											hi : 50
										},{
											color : "#000000",
											lo : 51,
											hi : 100
										}]
									},
									levelColors: ["#CE1B21", "#D0532A", "#FFC414", "#85A137"],
									counter: true
									});

							} );
						</script>
I had to use ranges AND levelColors for some reason.  If i remove one it doesn't work.

**Comment by kievsash** [comment]
Config, that worked for me:

```
  config = {
    value: 0,
    min: 0,
    max: 600000,
    decimals: 0,
    gaugeWidthScale: 0.6,
    label: '$',
    formatNumber: true,
    customSectors: {
      percents: true,
      ranges: [
        {lo: 0, hi: 33, color: '#13ED5A'}, // lo and hi values are in %
        {lo: 34, hi: 67, color: '#49D61C'},
        {lo: 68, hi: 100, color: '#49AB1C'}
      ]
    }
  };
```
