### ISSUE TITLE
Gauge Titles vanished. Upgraded from 1.2.2 to 1.2.9

### ISSUE THREAD

**Issue by tomrbland** [toorshia/justgage#284]
Any ideas why all of my gauge titles vanish if I go from 1.2.2 to 1.2.9? No code changes, just changed the file path to the JS.

**Comment by Mike55555** [comment]
Exact same problem here. Anyone got any thoughts on how to fix?

**Comment by Mike55555** [comment]
Ah, I just saw the release history notes - apparently the title feature was removed in 1.2.6!  https://github.com/toorshia/justgage/releases

**Comment by Mike55555** [comment]
To restore the title, I added it on my page above the JustGage DIV, and gave it the following style to match the earlier title feature.

.JustGage_Title
{
    text-align:center;
    font-family: Arial; font-size: 20px; font-weight: bold; 
    color:#999999;
}
