### ISSUE TITLE
ASP.NET Webforms Render Issue

### ISSUE THREAD

**Issue by etatmirtna** [toorshia/justgage#294]
I tried adding multiple gauges to report the size of 4 databases side-by-side on a basic asp.net webforms page and no matter what I do the gauges all line up in a column and push everything down.  The gauges all work correctly - I just cannot position them.  Another page is designed to display the table sizes in these databases in a row column format.  I've tried various forms of css to no avail.  Anyone else have this issue or can you think of some interaction with Bootstrap, jQuery, etc... that I need to adjust???

Thanks

**Comment by MvErven** [comment]
Try the inline styling option. Have a look at "autoadjust.htm" in the example folder. Hope this may help.

**Comment by etatmirtna** [comment]
Sorry haven't had time to respond.  I figured it out.  Nothing wrong with the gauge at all.  When I was rendering the JavaScript I didn't catch that I had missed declaring the gauge uniquely.  So I had generated unique gauge id' on the declaration but overlooked the inner id...it was always gg1 for example.  This had the unique effect of lining all the gauges up in a line down the page and threw me for a loop.  Once I saw my mistake and corrected it they all gridded up nicely.  It's a great piece of work and is very fast to render.  

But you can close this ticket/request and chalk it up to old eyes.

Thanks!

**Comment by MvErven** [comment]
Great to hear you solved it. But I can't close issues ;)
