### ISSUE TITLE
Adding + sign when value is positive

### ISSUE THREAD

**Issue by thierry-dosseto** [toorshia/justgage#295]
Hello folks,
Is there any way a '+' sign could be added in front of a positive value ?

If I graph from -100 to 100, and choose let's say -27, the minus sign is displayed.
But if I want to show a trend, like +26%, I can only get 26% displayed.

Any hint ?

**Comment by thierry-dosseto** [comment]
No one ?

**Comment by R3cycl0r** [comment]
I'm with you

**Comment by akhchan99** [comment]
you may use textRenderer

```
textRenderer: (v) => {
  return (v > 0 ? '+' : '') + v
}
```

**Warning:** you'll loose all the other formatting, ie. decimals, symbol etc, add all those into your textRenderer if  needed

**Comment by thierry-dosseto** [comment]
akhchan99 thank you very much, but I'm afraid I do not know how to use it :-(

**Comment by akhchan99** [comment]
just add it as one of the property of the justgage config options
ie

```
var config = {
  min: 0,
  max: 100,
  label: 'value',
  value: 65,
  decimals: 0,
  gaugeWidthScale: 1,
  id: 'gauge',
  title: 'test',
  textRenderer: (v) => {
    return (v > 0 ? '+' : '') + v
  }
};
```

**Comment by thierry-dosseto** [comment]
Ho ok !

I'll give it a try thank you very much !

**Comment by thierry-dosseto** [comment]
Hum I probably did it wrong since no + sign is showing 👍 
<script src="/Infocentre/scripts/jquery-3.2.1.min.js"></script>

<script>
$(document).ready(function(){
      var g1 = new JustGage({
        id: 'g1',
        pointer: true,
        gaugeWidthScale: 0.6,
        levelColors: ['#0F0'],
        counter: true,
        titleFontColor: '#000000',
        labelFontColor: '#000000',
        gaugeColor: '#303030',
        shadowOpacity: 1,
        shadowSize: 5,
        startAnimationTime: 3200,
        startAnimationType: ">",
        shadowVerticalOffset: 10,
        textRenderer: (v) => {
        return (v > 0 ? '+' : '') + v
          }
      });

**Comment by akhchan99** [comment]
your sample doesn't have "value" property
check this jsfiddle
http://jsfiddle.net/ugFmE/379/

**Comment by thierry-dosseto** [comment]
No since values (almost 30 counters on the page) are generated by PHP :

<div class="gauche-33-stats">
                <div id="g1" class="gauge" data-min="0" data-max="<?php echo $total_annuel_max;?>" data-title="Nombre total de passages <?php echo $annee_moins_deux;?>" data-value="<?php echo $total_annuel_annee_moins_deux;?>"></div>
        </div>

**Comment by akhchan99** [comment]
not familiar with php, so can't help you with that..you may look at the jsfiddle and see how you can integrate it...justgage expect a "float" as value, is your mapping going to change that?

**Comment by thierry-dosseto** [comment]
Well one of the most powerful feature of justgage is that you can display calculated values.

Those counters are part of a Business Intelligence platform I developped, and all the values displayed by those counters are extracted from databases and calculated in real time.

So as you can see, one part of the counter is in the javascript (all the fixed values like color, animation, etc ...) and the rest is dynamic (it is in the DIV (so the html with values calculated and inserted by php).

Don't waste your time with my problem, you showed me the right path, I'll find out.

Thank you !
