### ISSUE TITLE
dynamically creating multiple gauges...

### ISSUE THREAD

**Issue by tamaker** [toorshia/justgage#298]
awesome project, thanks for sharing it looks / works great.   My question / issue is I'm dynamically creating instances of JustGage and have an ID (number) that I'm trying to use when the array loop detects a NEW instance is required...

I'm having a problem when trying to create a dynamic object variable to serve as the new JustGage instance... 

'var myDynamicIdx = 'g'+myArray.idNum;    // THE UNIQUE VARIABLE NAME FOR THE OBJECT
`myDynamicIdx = new JustGage({...`    // HOW DO I USE THE VARIABLE NAME FOR THE NEW INSTANCE?

outside of my loop where I create the instance, where I find it already exists, i then want to fire the update function, 

`updateGauge(gaugeID, thisArrayItem.cpu)`

with all of this as a static page and data It works fine, the issue seems to be where i need to dynamically assign the values for g1, g2, g3, etc.

**Comment by grabekws** [comment]
+1 
I'm also trying to dynamically create Justgages but so far without success.

**Comment by dico** [comment]
I added mine into an array.

`<script>
var charts = [];

function create charts()
{
    $(".gauge").each(function(){
        var entity_id = $(this).attr('id');
        var gauge_max = $(this).data('max');
        var gauge_min = $(this).data('min');
        var title = $(this).data('title');
        
        charts.push(
            new JustGage({
                id: entity_id,
                value: 0,
                min: gauge_min,
                max: gauge_max,
                title: title,
            })
        );
    });
}

function update_charts()
{
    $(charts).each(function(){
        this.refresh(Math.random() * (1000 - 0) + 0);
    });
}
</script>

<div class="gauge" id="gauge000001" data-min="0" data-max="1000 data-title="SomeTitle01"></div>
<div class="gauge" id="gauge000002" data-min="0" data-max="2000 data-title="SomeTitle02"></div>`

**Comment by robertsLando** [comment]
You can try with @dico solution
