### ISSUE TITLE
Start Gauge When User Views it

### ISSUE THREAD

**Issue by phpmods** [toorshia/justgage#299]
Can we set the gauges to start loading when the user views the part of the page where the gauge is? We have placed the gauges lower in a website but the user does not see any movement when he scrolls down the page after a few seconds.

Is this something that can be done?

**Comment by robertsLando** [comment]
If you are using jquery: 

```js
$('#yourGauge').appear(function() {
 var g = new Justgage(options)
...
});
```

Otherwise check the answer on stackoverflow https://stackoverflow.com/questions/487073/how-to-check-if-element-is-visible-after-scrolling
