### ISSUE TITLE
Enhancement: ability to add a target value, thresholds

### ISSUE THREAD

**Issue by Ianfeather** [toorshia/justgage#3]
Great job with this, really nice. I'm interested in using this to display real time (or near real time) metrics. For us, I think being able to set and visualise a target value that we want to hit, or a threshold that we need to stay inside would be really cool. Plus as an aside, being able to alert on leaving that threshold so that we can act on it.

I've forked the repo but if you have any ideas on this it'd be great to hear them. Will let you know I get on.

**Comment by sankarasr** [comment]
Hello,
 http://bit.ly/15RBkKe is showing 404.  I wanted a speedometer kind of gauge with thresholds on which the pointer moves. Please inform if this is already implemented or will be implemented in the future.
