### ISSUE TITLE
Not able to use justgage in react component

### ISSUE THREAD

**Issue by sarkariajatt** [toorshia/justgage#315]
Hi i am trying to use the justgage in react component and i am importing justgage and raphael in that component and even then i am getting an error that JustGage is not defined, getRandom is not defined.
import React,{Component}from 'react';
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import '../../node_modules/jquery-ui-stable/jquery-ui.min.css';
import '../../node_modules/justgage/raphael-2.1.4.min.js';
import '../../node_modules/justgage/justgage.js';

**Comment by osvaldoalvaradodev** [comment]
Same problem :(

**Comment by robertsLando** [comment]
Now justgague has been modularized so you can import it like others modules

`import 'justgage'`
