### ISSUE TITLE
minTxt and maxTxt not working

### ISSUE THREAD

**Issue by MrCraftfreak** [toorshia/justgage#316]
**The code below is the one i made but it doesn't show the minTxt and maxTxt**

<!doctype html>
<html>

<head>
  <meta charset="utf-8" />
  <title>Defaults</title>
  <meta name="viewport" content="width=device-width">
  <style>
  .container {
    width: 600px;
    margin: 100px auto;
    text-align: center;
  }

  .gauge {
    width: 350px;
    height: 250px;
    display: inline-block;
  }

  </style>
</head>

<body>
  <div class="container">
    <div  id="gg1" class="gauge"></div>
  </div>
  <script src="https://fm2.loggix.com/raphael-2.1.4.min.js"></script>
  <script src="https://fm2.loggix.com/justgage.js"></script>
  <script>
  document.addEventListener("DOMContentLoaded", function(event) {

    var dflt = {
      min: 0,
      max: 200,
      minTxt: 'no',
      maxTxt: 'yes',      
      donut: false,
      gaugeWidthScale: 0.8,
      counter: true,
      hideInnerShadow: true
    }
    
    var gg1 = new JustGage({
      id: 'gg1',
      value: 50,
      title: 'test',
      defaults: dflt
    });
  });
  </script>
</body>

</html>

**Comment by robertsLando** [comment]
`minTxt` and `maxTxt` overrides `min` and `max` values
