### ISSUE TITLE
Error in raphael 2.1.4 js

### ISSUE THREAD

**Issue by RitterD** [toorshia/justgage#317]
Hi,

first of all I like the function and design of your gauge realy much and its perfect for my usage.
But everytime I call the function to draw the gauge I receiving this Error:
raphael-2.1.4.min.js:10  Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "Z".

![grafik](https://user-images.githubusercontent.com/37876396/42751809-46ba2d5e-88ec-11e8-9601-82bc18c487d7.png)

Here is the function in JS:
`
function Vibration(val) {

    var gauge = new JustGage({
        id: "g1",
        value: val,
        min: 0,
        max: 100,
        title: "Vibration"
    });
}
`

HTML:
`<div id="g1" class="200x160px"></div>`

Thank you very much in advance!

**Comment by andrelec1** [comment]
Same here.
