### ISSUE TITLE
Refresh Justgage with new setting , e.g new Custom Sector ???

### ISSUE THREAD

**Issue by coidien** [toorshia/justgage#324]
Hi everyone,
Is there a way to refresh justgage with new custom Sector. I can only found refresh with new maximum like: g.refresh(new value, new maximum). 
In my Page there is 4 button for 4 Mode and each Mode has own Setting (Max, Min and Custom Sector) for Justgage. And when button is clicked, gauge with own Setting appear.

Do anyone know how to do this ?

**Comment by robertsLando** [comment]
ATM the only way to do this is by destroy and recreate a new gauge when customSector changes, in next release we will implement #241 that will allow you to do this kind of things
