### ISSUE TITLE
How can I set the speed of the animation or disable the animation?

### ISSUE THREAD

**Issue by Chalkim** [toorshia/justgage#327]
Hi, Here is the problem that I'm facing. The data I refeshed varys quickly, like about 20%/100ms or more. But the animation is too slow to keep pace with the varying data. I wonder if I can set the speed of animation or just disable it, so the data can be displayed accurately.

**Comment by robertsLando** [comment]
@Chalkim Use the option `refreshAnimationTime`, check [Options](https://github.com/toorshia/justgage#options) for more info
