### ISSUE TITLE
Library Update

### ISSUE THREAD

**Issue by brunotourinho** [toorshia/justgage#328]
Hello!
First I'd like to say, that I love this library and I'm using it in some production projects.
It's been such a long time since we had an update.
Is there any plans to update it in a near future or if is there any other alternative repo/fork that you are using?

Thanks in advance to Mr. @toorshia and all the contributors

**Comment by robertsLando** [comment]
I'm helping @toorshia to keep it updated now.

**Comment by brunotourinho** [comment]
Very nice @robertsLando! Thank you!
