### ISSUE TITLE
eve is not defined

### ISSUE THREAD

**Issue by D252874** [toorshia/justgage#329]
ERROR ReferenceError: eve is not defined
    at new JustGage (justgage.js:791)
i don't know what to do

**Comment by dmikhalsky** [comment]
the same

**Comment by dmikhalsky** [comment]
need to use Raphael 2.2.7
Works now

**Comment by robertsLando** [comment]
Fixed with 81cff4cd1ef3a57df5575421730b67a2aa3207de
