### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by nicolas-van** [toorshia/justgage#330]
The demos on the website https://justgage.com/ simply don't work anymore. They display nothing at all.

Tested on Chrome 75 and Firefox 68: same result.

According to the logs it seems to be a quite classical http/https mixed content problem. It could probably be fixed easily by switching to https for all your cdn dependencies.

**Comment by deezone** [comment]
Confirmed...

![image](https://user-images.githubusercontent.com/2119264/62135109-a217cb00-b2af-11e9-9509-b0633bc8eb29.png)

**Comment by robertsLando** [comment]
Unfortunally I don't have any access to the demo code. I try to ask @toorshia to fix that

**Comment by toorshia** [comment]
@nicolas-van thanks for reporting, should be fixed now - please check.
