### ISSUE TITLE
REQUEST:  Add target value

### ISSUE THREAD

**Issue by schmeed** [toorshia/justgage#334]
I would like to request a feature where I can set a range (i.e. 0-100) and also set a target value (i.e. 75).  The gauge moves between 0-100 as normal and the setpoint remains static.

If this is already possible, please let me know.

**Comment by schmeed** [comment]
Bump?

**Comment by robertsLando** [comment]
This is already in our todo list, do you have a pr (pull request) to send? If not you have to wait 

Daniel

**Comment by schmeed** [comment]
> This is already in our todo list, do you have a pr (pull request) to send? If not you have to wait Daniel
> […](#)
> On 28 Oct 2019, at 14:03, schmeed ***@***.***> wrote: ﻿ Bump? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you.  Apologies for the naive question, does a pull request mean I've developed the code for you to incorporate?

**Comment by schmeed** [comment]
Please disregard.  I read about pull requests and understand now how the process works.  I'll look through the code but I'm not a javascript developer so I'll likely wait.

Happy to test when the feature is ready.

**Comment by robertsLando** [comment]
We will do our best thanks! 😊

Daniel

**Comment by schmeed** [comment]
> We will do our best thanks! 😊 Daniel
> […](#)
> On 28 Oct 2019, at 14:36, schmeed ***@***.***> wrote: ﻿ This is already in our todo list, do you have a pr (pull request) to send? If not you have to wait Daniel … On 28 Oct 2019, at 14:03, schmeed @.***> wrote: ﻿ Bump? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Thank you. Apologies for the naive question, does a pull request mean I've developed the code for you to incorporate? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Hello, it's been a couple years, just curious if there are any updates?

**Comment by robertsLando** [comment]
Currently I have no time for new features, I focus on bug fixes

**Comment by Alloyd21** [comment]
Added
#398
