### ISSUE TITLE
How to show actual percentage value 

### ISSUE THREAD

**Issue by vasuthammaiah** [toorshia/justgage#335]
Hi ,

How to show actual percentage calculated in the gauge . example if min:0 and max:80 and value :80 then percentage should be 100% not 80(value)

or Min: 0 , Max:17 and value :2 then i want display calculated percentage instead of 2

![gaggue](https://user-images.githubusercontent.com/10817280/67464659-0692be00-f644-11e9-927d-997b57b6daf8.png)

Thanks
Vasu

**Comment by robertsLando** [comment]
Try using “ textRenderer” 

Daniel
