### ISSUE TITLE
update() commit breaks the ^1.3.3 usability on wxWidgets WebView

### ISSUE THREAD

**Issue by canne** [toorshia/justgage#342]
Hi, many thanks for the great gauge that I like very much! I am using 1.3.3 on a [wxWidgets WebView](https://docs.wxwidgets.org/3.0/classwx_web_view.html) window, on different platforms (Linux, Windows and, eventually Mac and Android). This is to report that since the [Merge pull request #340 from deezone/Issue-241](https://github.com/toorshia/justgage/commit/ff32c9a5cbf4c41608876d7cf4bb6f3c0cb4ef90#) it has stopped working both on Linux and Windows wxWidgets WebView. They have quite (very) old rendering back-ends both, IE (sic) for Windows and an WebKit1x for Linux. This is not a modern browser application, as you can see. The two culprits for the failure which I found are the lonely `const` ([1009](https://github.com/toorshia/justgage/blob/ac84e89729c79a0e89f1517ed52325b2f201450b/justgage.js#L1009)) and unconventional string limiters ([1063](https://github.com/toorshia/justgage/blob/ac84e89729c79a0e89f1517ed52325b2f201450b/justgage.js#L1063)).

In my application I change the color scheme with SCSS from 'day' 'to 'dusk' to 'night' and to have a way to change the value and label colors in _justgage_ would be highly appreciated also on older platforms.

**Comment by robertsLando** [comment]
@canne Fixed in 1.3.4
