### ISSUE TITLE
[feat] Differential gauge

### ISSUE THREAD

**Issue by robertsLando** [toorshia/justgage#345]
More info here: https://discourse.nodered.org/t/differential-gauge-node-a-proposal-for-a-new-appearance/21449/6

**Comment by robertsLando** [comment]
@deezone Would you likw to implement this? just need to edit the `pki` function and add a new property 'differential` to gauge options

**Comment by leemind** [comment]
I would love this feature - in fact for exactly the same use case.

**Comment by robertsLando** [comment]
PR?

**Comment by leemind** [comment]
> PR?
I think you are giving me far too much credit - I don't think my coding skill are up to it!

**Comment by leemind** [comment]
OK, so I have a working prototype in my forked repo.  It only works when min = -max at the moment, and I need to do some more testing, but when I am happy, I'll put in a PR

**Comment by robertsLando** [comment]
Open a PR and I will give it a look

**Comment by Langer75** [comment]
Hi, I am also looking for this feature. I can also do some testing

**Comment by Indiana8000** [comment]
@leemind I'm testing your implementation as this is one of my desperately needed features. So long looks very good!

**Comment by leemind** [comment]
Ha, I had forgotten that I had pushed it to github. I don't think I even documented it properly. I do want to add 2 pointers on one guage as well. Let me know how you get on On 28 Nov 2022 12:53, Andreas Kreisl ***@***.***> wrote:
@leemind I'm testing your implementation as this is one of my desperately needed features. So long looks very good!

**Comment by robertsLando** [comment]
@leemind Could you open a PR?

**Comment by robertsLando** [comment]
Available on [1.6.0](https://github.com/toorshia/justgage/releases/tag/v1.6.0)
