### ISSUE TITLE
Converting JustGage to PDF

### ISSUE THREAD

**Issue by altjx** [toorshia/justgage#348]
RE: #243 

I am having issues converting a justgage chart to PDF along with an HTML file that the gauge appears in.  For example, if this is the HTML file: https://jsfiddle.net/ue8x5ym1/1/ and I try to convert that HTML file to a PDF with wickedhtmltopdf, it doesn't work.

I don't think this is a particular issue with JustGage per se, but I'm wondering if there are any options with JustGage that I can set to make this work since other charts work just fine. I've tried setting the animations to 0 just like the reference, but no luck. 

Any additional suggestions would be greatly appreciated.

**Comment by robertsLando** [comment]
Check out this: https://stackoverflow.com/questions/23681325/convert-canvas-to-pdf

**Comment by altjx** [comment]
Thanks @robertsLando
