### ISSUE TITLE
Gauge Chart Ranges

### ISSUE THREAD

**Issue by MartijnHarmenzon** [toorshia/justgage#351]
Is it possible to make something like the image below with the Gauge Chart?

![image](https://user-images.githubusercontent.com/23123158/84003141-de08cb80-a969-11ea-992c-832650a9a4e9.png)

For example, I would like to have five performance ranges: 0-20, 20-40, 40-60, 60-80 and 100-120. Each range will have it's own color. For example 0-20 is green and 100-120 is red. Preferably showing the ranges as labels on the chart.

Possible overlap with #170

**Comment by robertsLando** [comment]
Actually this is not possible, would you like to send a PR?

**Comment by MartijnHarmenzon** [comment]
Thanks for the quick reply. I was hoping it to be part of v2. I will continue watching #170. I believe some work is done there?

**Comment by robertsLando** [comment]
Actually I have no time for new features, I just try to keep deps updated and fix bugs
