### ISSUE TITLE
Feature request: Add the possibility to change font family for the MIN and MAX labels

### ISSUE THREAD

**Issue by spacecat** [toorshia/justgage#356]
First of all, awesome script, great work bro.

Second, I could customize everything I wanted to customize except the font family for the MIN and MAX labels.

Would it be possible to add this feature in the future?

**Comment by robertsLando** [comment]
@spacecat WOuld you like to submit a pr?

**Comment by spacecat** [comment]
I would if I had the time :) but currently I'm working on like 10 projects or so so no can do... sorry ;(
