### ISSUE TITLE
Gauges don't respond to window resize in fluid layouts

### ISSUE THREAD

**Issue by erquhart** [toorshia/justgage#39]
In fluid layouts, everything updates when the window is resized, maximized, etc - but the gauges don't adjust.  I might be blanking on something that should be handled in the layout itself, but I really can't think of anything.

Using fluid layout in Bootstrap.

**Comment by rclaes1995** [comment]
I've got the same issue as in this thread. Using bootstrap, enabled relativeGaugeSize but it's not resizing. Anyone found a fix? I do not want to use an absolute positioned wrapper...
