### ISSUE TITLE
Possible issue with pki function when dy is non-zero causes gauge to calculate arc path wrong

### ISSUE THREAD

**Issue by devmonkey22** [toorshia/justgage#73]
I am using version dated 31/07/2012 version 1,0.

I think I found an issue where the pki function miscalculates the Yo and Yi values when dy is non-zero.   For example, Yo's calculation is "h - (h - Cy) + dy - Ro * Math.sin(alpha)" however I believe that dy should be removed because Cy already translates Cy by dy, so Yo was being double translated by dy in effect.   Same goes for Yi.

Thanks,
Mike Dearman

**Comment by toorshia** [comment]
https://github.com/toorshia/justgage/issues/245
