### ISSUE TITLE
From positive to negative values

### ISSUE THREAD

**Issue by denniedegroot** [toorshia/justgage#83]
I have initialized my graph with a min value of 0. When using positive numbers there is no problem. But when I refresh the value with a negative number the graph will not fill the bar. So the min value is still 0, max value is set on -1000 and the value -500.

 Is there maybe a way to 'invert' the filling when using a negative number?

**Comment by JustAGuyTryingToCodeSomething** [comment]
I was wondering about this too. 

You can use the textRenderer callback function to pre-format the gage's display value with a '-'. 

Changing the gage's min and max labels requires a code change, a callback for these might be nice too. A quick and dirty method is to add a new preSymbol config option, as a counter part to the existing (post) Symbol option, and pre-format the relevant labels with it. 

Obviously the gage still thinks it's showing 0 to 1000, but it'll be labelled 0 to -1000.

**Comment by toorshia** [comment]
Watch #248
