### ISSUE TITLE
Responsive gage not sizing correctly in IE8

### ISSUE THREAD

**Issue by cibgraphics** [toorshia/justgage#87]
I am trying to get a responsive gage to work in IE8+, and I got it to work in every browser minus IE8. The gage displays, but doesn't expand to fill the contents of it's parent.

![screen shot 2013-10-03 at 11 22 42 am](https://f.cloud.github.com/assets/972737/1263514/c5533924-2c50-11e3-9606-aeff0a0104c0.png)

I looked at the responsive demo, and the gage didn't even display on the demo. It does work on IE9+

**Comment by toorshia** [comment]
Stopping <IE9 support.
